# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: local
      hooks:
          - id: format-isort
            name: Isort Formatting
            description: Run formatting using isort
            entry: isort
            language: system
            types: [python]
            args: [.]
          - id: format-black
            name: Black Formatting
            description: Run formatting using black
            entry: black
            language: system
            types: [python]
            args: [.]
